### ISSUE TITLE
Project Build Error?

### ISSUE THREAD

**Issue by ShooterArk** [eluleci/FlatUI#1]
Hi, Im trying to implement the flatUI on my android app, but if you build it, it gives some build error, secondly there is no clear description how to use it on eclipse since I am not using android studio. Please advise. Thanks

**Comment by eluleci** [comment]
Hi, I am going to update the project (but not so soon) for supporting gradle and eclipse too. I'll let you know when I can do it.

**Comment by ShooterArk** [comment]
Well Eluleci I would really appreciate if you upload it asap as I need to implement it by the end of January. Thanks in Advance

**Comment by eluleci** [comment]
Hello, I assume that the error that you have is not build error but runtime error. Since that the library contains font files in assets folder there appears this problem if project doesn't include the assets of library. 

It is possible to 'include library assets' in Android Studio (not gradle build) but there is no option like that in eclipse. But there is really simple solution.

You can fix this issue with copying the fonts folder of the library into your assets folder. Then the error should be solved. If you have any other error, can you please send me log message of that error.

Thanks

**Comment by eluleci** [comment]
Can you let me know when you successfully build your app. I am waiting for your response to close this issue. Thanks.

**Comment by ShooterArk** [comment]
Yes I have tried it on a demo app and its works just fine. But I have not
yet test it on a real device. So I guess it is working fine now. Thanks
alot for your help.

**Comment by eluleci** [comment]
I am happy to hear it. By the way I migrated project to Gradle and trying to put the library in maven central. If you use Gradle in few days you can add it as dependency to your project.

**Comment by ShooterArk** [comment]
Thanks for the updates. I will do that and will contact you if I got in
some problem again ;) . Thanks alot once again.
